/* gl_thunks.h -- the guest->host GL/EGL boundary.
 *
 * gl_thunks.c is generated by loader/mkglthunks.py from devkitPro's GLES and
 * EGL headers; this is the hand-written support around it. Only built for the
 * Switch target: the host differential harness has no GLES to link against,
 * and the CPU differential does not need one.
 */
#ifndef GL_THUNKS_H
#define GL_THUNKS_H

#include <stdint.h>

#include "guest.h"

typedef struct {
    const char *name;
    GuestHleFn  fn;
} GlThunk;

extern const GlThunk g_gl_thunks[];
extern const unsigned g_gl_thunk_count;

/* Returns the thunk for an import name, or NULL if it is not a GL/EGL entry
 * point this layer covers. EGL names resolve to the hand-written overrides in
 * gl_egl.c first -- the generated EGL thunks truncate 64-bit host handles into
 * 32-bit guest registers and cannot be made correct. */
GuestHleFn gl_find_thunk(const char *name);

/* The hand-written EGL layer (gl_egl.c). NULL for a name it does not cover. */
GuestHleFn egl_find_override(const char *name);

/* The harness lends its guest allocator so returned strings can live in guest
 * memory. Must be called before any thunk runs. */
void gl_set_allocator(uint32_t (*alloc)(uint32_t));

/* Copy a host C string into guest memory and hand back a guest address -- a
 * 64-bit host pointer cannot be represented to a 32-bit guest. GL returns the
 * same static strings over and over, so results are cached by host pointer. */
uint32_t gl_return_cstr(GuestMem *m, const char *s);

/* Nothing on the GLES1 path returns a bare host pointer. If something does,
 * say so loudly rather than truncating it into a plausible-looking address. */
void gl_unsupported_ptr_return(const char *name);

/* A GLES2/3-only entry point, absent from the fixed-function library this
 * build links. */
void gl_unimplemented(const char *name);

#endif /* GL_THUNKS_H */
