/* GENERATED by loader/mkglthunks.py -- do not edit by hand.
 *
 * Guest (ARM32 softfp) -> host (AArch64) shims for the GL/EGL imports.
 * Regenerate after changing the import set or the GLES headers. */
#include <stdint.h>
#include <string.h>

#include <GLES/gl.h>
#include <GLES/glext.h>
#include <EGL/egl.h>
#include <EGL/eglext.h>

#include "guest.h"
#include "gl_thunks.h"

/* Argument fetch. Slots 0-3 are r0-r3, the rest come off the guest
 * stack. A 64-bit value needs an even-aligned pair. */
static uint32_t ga(GuestCpu *c, GuestMem *m, unsigned slot) {
    uint32_t v = 0;
    if (slot < 4)
        return c->r[slot];
    guest_ld32(m, c->r[GUEST_SP] + 4u * (slot - 4u), &v);
    return v;
}

/* A guest pointer with no known extent: length 1 is enough to locate
 * the host mapping, and the region is contiguous from there. NULL
 * stays NULL so the driver sees the same thing the game passed. */
static void *gp(GuestMem *m, uint32_t addr) {
    return addr ? guest_ptr(m, addr, 1) : NULL;
}

static float gf(uint32_t bits) {
    float f;
    memcpy(&f, &bits, 4);
    return f;
}

static void t_glRenderbufferStorage(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glRenderbufferStorage");
    c->r[0] = 0;
}

static void t_glGetRenderbufferParameteriv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glGetRenderbufferParameteriv");
    c->r[0] = 0;
}

static void t_glGetFramebufferAttachmentParameteriv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glGetFramebufferAttachmentParameteriv");
    c->r[0] = 0;
}

static void t_glBindRenderbuffer(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glBindRenderbuffer");
    c->r[0] = 0;
}

static void t_glGenerateMipmap(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glGenerateMipmap");
    c->r[0] = 0;
}

static void t_glBindFramebuffer(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glBindFramebuffer");
    c->r[0] = 0;
}

static void t_glFramebufferRenderbuffer(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glFramebufferRenderbuffer");
    c->r[0] = 0;
}

static void t_glDeleteRenderbuffers(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glDeleteRenderbuffers");
    c->r[0] = 0;
}

static void t_glFramebufferTexture2D(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glFramebufferTexture2D");
    c->r[0] = 0;
}

static void t_glGenRenderbuffers(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glGenRenderbuffers");
    c->r[0] = 0;
}

static void t_glCheckFramebufferStatus(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glCheckFramebufferStatus");
    c->r[0] = 0;
}

static void t_glIsRenderbuffer(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glIsRenderbuffer");
    c->r[0] = 0;
}

static void t_glIsFramebuffer(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glIsFramebuffer");
    c->r[0] = 0;
}

static void t_glDeleteFramebuffers(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glDeleteFramebuffers");
    c->r[0] = 0;
}

static void t_glGenFramebuffers(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glGenFramebuffers");
    c->r[0] = 0;
}

static void t_eglQueryString(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = gl_return_cstr(m, (const char *)eglQueryString((EGLDisplay)ga(c, m, 0), (EGLint)ga(c, m, 1)));
}

static void t_glStencilMaskSeparate(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glStencilMaskSeparate");
    c->r[0] = 0;
}

static void t_glUseProgramStages(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUseProgramStages");
    c->r[0] = 0;
}

static void t_eglCreateContext(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)eglCreateContext((EGLDisplay)ga(c, m, 0), (EGLConfig)ga(c, m, 1), (EGLContext)ga(c, m, 2), (const EGLint *)gp(m, ga(c, m, 3)));
}

static void t_glFogxv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glFogxv((GLenum)ga(c, m, 0), (const GLfixed *)gp(m, ga(c, m, 1)));
}

static void t_glFramebufferTextureLayer(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glFramebufferTextureLayer");
    c->r[0] = 0;
}

static void t_glClear(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glClear((GLbitfield)ga(c, m, 0));
}

static void t_glClearColorx(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glClearColorx((GLfixed)ga(c, m, 0), (GLfixed)ga(c, m, 1), (GLfixed)ga(c, m, 2), (GLfixed)ga(c, m, 3));
}

static void t_glNormalPointer(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glNormalPointer((GLenum)ga(c, m, 0), (GLsizei)ga(c, m, 1), (const void *)gp(m, ga(c, m, 2)));
}

static void t_glMaterialfv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glMaterialfv((GLenum)ga(c, m, 0), (GLenum)ga(c, m, 1), (const GLfloat *)gp(m, ga(c, m, 2)));
}

static void t_glStencilFunc(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glStencilFunc((GLenum)ga(c, m, 0), (GLint)ga(c, m, 1), (GLuint)ga(c, m, 2));
}

static void t_glFogf(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glFogf((GLenum)ga(c, m, 0), (GLfloat)gf(ga(c, m, 1)));
}

static void t_glMultiTexCoord4f(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glMultiTexCoord4f((GLenum)ga(c, m, 0), (GLfloat)gf(ga(c, m, 1)), (GLfloat)gf(ga(c, m, 2)), (GLfloat)gf(ga(c, m, 3)), (GLfloat)gf(ga(c, m, 4)));
}

static void t_glUseProgram(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUseProgram");
    c->r[0] = 0;
}

static void t_glRotatef(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glRotatef((GLfloat)gf(ga(c, m, 0)), (GLfloat)gf(ga(c, m, 1)), (GLfloat)gf(ga(c, m, 2)), (GLfloat)gf(ga(c, m, 3)));
}

static void t_glDisable(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glDisable((GLenum)ga(c, m, 0));
}

static void t_glCullFace(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glCullFace((GLenum)ga(c, m, 0));
}

static void t_glClearStencil(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glClearStencil((GLint)ga(c, m, 0));
}

static void t_eglGetCurrentDisplay(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)eglGetCurrentDisplay();
}

static void t_glDepthRangex(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glDepthRangex((GLfixed)ga(c, m, 0), (GLfixed)ga(c, m, 1));
}

static void t_glDeleteBuffers(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glDeleteBuffers((GLsizei)ga(c, m, 0), (const GLuint *)gp(m, ga(c, m, 1)));
}

static void t_glLightModelxv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glLightModelxv((GLenum)ga(c, m, 0), (const GLfixed *)gp(m, ga(c, m, 1)));
}

static void t_glOrthox(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glOrthox((GLfixed)ga(c, m, 0), (GLfixed)ga(c, m, 1), (GLfixed)ga(c, m, 2), (GLfixed)ga(c, m, 3), (GLfixed)ga(c, m, 4), (GLfixed)ga(c, m, 5));
}

static void t_eglGetDisplay(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)eglGetDisplay((EGLNativeDisplayType)ga(c, m, 0));
}

static void t_glEnableClientState(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glEnableClientState((GLenum)ga(c, m, 0));
}

static void t_glColor4f(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glColor4f((GLfloat)gf(ga(c, m, 0)), (GLfloat)gf(ga(c, m, 1)), (GLfloat)gf(ga(c, m, 2)), (GLfloat)gf(ga(c, m, 3)));
}

static void t_glPointSize(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glPointSize((GLfloat)gf(ga(c, m, 0)));
}

static void t_glGetUniformLocation(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glGetUniformLocation");
    c->r[0] = 0;
}

static void t_glDepthMask(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glDepthMask((GLboolean)ga(c, m, 0));
}

static void t_glDisableClientState(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glDisableClientState((GLenum)ga(c, m, 0));
}

static void t_glVertexAttribIPointer(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glVertexAttribIPointer");
    c->r[0] = 0;
}

static void t_glBindTexture(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glBindTexture((GLenum)ga(c, m, 0), (GLuint)ga(c, m, 1));
}

static void t_glLineWidth(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glLineWidth((GLfloat)gf(ga(c, m, 0)));
}

static void t_glPopMatrix(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glPopMatrix();
}

static void t_glMaterialx(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glMaterialx((GLenum)ga(c, m, 0), (GLenum)ga(c, m, 1), (GLfixed)ga(c, m, 2));
}

static void t_glCompressedTexSubImage3D(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glCompressedTexSubImage3D");
    c->r[0] = 0;
}

static void t_eglQuerySurface(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)eglQuerySurface((EGLDisplay)ga(c, m, 0), (EGLSurface)ga(c, m, 1), (EGLint)ga(c, m, 2), (EGLint *)gp(m, ga(c, m, 3)));
}

static void t_eglMakeCurrent(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)eglMakeCurrent((EGLDisplay)ga(c, m, 0), (EGLSurface)ga(c, m, 1), (EGLSurface)ga(c, m, 2), (EGLContext)ga(c, m, 3));
}

static void t_glBufferData(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glBufferData((GLenum)ga(c, m, 0), (GLsizeiptr)ga(c, m, 1), (const void *)gp(m, ga(c, m, 2)), (GLenum)ga(c, m, 3));
}

static void t_glClientActiveTexture(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glClientActiveTexture((GLenum)ga(c, m, 0));
}

static void t_glBlendColor(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glBlendColor");
    c->r[0] = 0;
}

static void t_eglGetConfigAttrib(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)eglGetConfigAttrib((EGLDisplay)ga(c, m, 0), (EGLConfig)ga(c, m, 1), (EGLint)ga(c, m, 2), (EGLint *)gp(m, ga(c, m, 3)));
}

static void t_glFogx(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glFogx((GLenum)ga(c, m, 0), (GLfixed)ga(c, m, 1));
}

static void t_glTexEnvi(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glTexEnvi((GLenum)ga(c, m, 0), (GLenum)ga(c, m, 1), (GLint)ga(c, m, 2));
}

static void t_glGetShaderInfoLog(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glGetShaderInfoLog");
    c->r[0] = 0;
}

static void t_glLightModelx(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glLightModelx((GLenum)ga(c, m, 0), (GLfixed)ga(c, m, 1));
}

static void t_glGenVertexArrays(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glGenVertexArrays");
    c->r[0] = 0;
}

static void t_glTexSubImage3D(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glTexSubImage3D");
    c->r[0] = 0;
}

static void t_glTexImage2D(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glTexImage2D((GLenum)ga(c, m, 0), (GLint)ga(c, m, 1), (GLint)ga(c, m, 2), (GLsizei)ga(c, m, 3), (GLsizei)ga(c, m, 4), (GLint)ga(c, m, 5), (GLenum)ga(c, m, 6), (GLenum)ga(c, m, 7), (const void *)gp(m, ga(c, m, 8)));
}

static void t_glClearDepthx(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glClearDepthx((GLfixed)ga(c, m, 0));
}

static void t_glLightxv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glLightxv((GLenum)ga(c, m, 0), (GLenum)ga(c, m, 1), (const GLfixed *)gp(m, ga(c, m, 2)));
}

static void t_eglDestroyContext(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)eglDestroyContext((EGLDisplay)ga(c, m, 0), (EGLContext)ga(c, m, 1));
}

static void t_glDeleteProgramPipelines(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glDeleteProgramPipelines");
    c->r[0] = 0;
}

static void t_glGetQueryObjectuiv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glGetQueryObjectuiv");
    c->r[0] = 0;
}

static void t_glOrthof(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glOrthof((GLfloat)gf(ga(c, m, 0)), (GLfloat)gf(ga(c, m, 1)), (GLfloat)gf(ga(c, m, 2)), (GLfloat)gf(ga(c, m, 3)), (GLfloat)gf(ga(c, m, 4)), (GLfloat)gf(ga(c, m, 5)));
}

static void t_glGetIntegerv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glGetIntegerv((GLenum)ga(c, m, 0), (GLint *)gp(m, ga(c, m, 1)));
}

static void t_glMultMatrixf(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glMultMatrixf((const GLfloat *)gp(m, ga(c, m, 0)));
}

static void t_glBlendFuncSeparate(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glBlendFuncSeparate");
    c->r[0] = 0;
}

static void t_glUniform1f(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniform1f");
    c->r[0] = 0;
}

static void t_glTexParameteri(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glTexParameteri((GLenum)ga(c, m, 0), (GLenum)ga(c, m, 1), (GLint)ga(c, m, 2));
}

static void t_glMaterialf(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glMaterialf((GLenum)ga(c, m, 0), (GLenum)ga(c, m, 1), (GLfloat)gf(ga(c, m, 2)));
}

static void t_glUniform3iv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniform3iv");
    c->r[0] = 0;
}

static void t_glStencilFuncSeparate(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glStencilFuncSeparate");
    c->r[0] = 0;
}

static void t_glGenProgramPipelines(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glGenProgramPipelines");
    c->r[0] = 0;
}

static void t_glPixelStorei(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glPixelStorei((GLenum)ga(c, m, 0), (GLint)ga(c, m, 1));
}

static void t_glDrawBuffers(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glDrawBuffers");
    c->r[0] = 0;
}

static void t_eglGetError(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)eglGetError();
}

static void t_glUniform4iv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniform4iv");
    c->r[0] = 0;
}

static void t_glUniform1fv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniform1fv");
    c->r[0] = 0;
}

static void t_glBlendEquationSeparate(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glBlendEquationSeparate");
    c->r[0] = 0;
}

static void t_glAlphaFunc(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glAlphaFunc((GLenum)ga(c, m, 0), (GLfloat)gf(ga(c, m, 1)));
}

static void t_glBindTransformFeedback(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glBindTransformFeedback");
    c->r[0] = 0;
}

static void t_glUniformMatrix3fv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniformMatrix3fv");
    c->r[0] = 0;
}

static void t_glUniformMatrix2fv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniformMatrix2fv");
    c->r[0] = 0;
}

static void t_glLightModelf(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glLightModelf((GLenum)ga(c, m, 0), (GLfloat)gf(ga(c, m, 1)));
}

static void t_glClearDepthf(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glClearDepthf((GLfloat)gf(ga(c, m, 0)));
}

static void t_glDisableVertexAttribArray(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glDisableVertexAttribArray");
    c->r[0] = 0;
}

static void t_glCopyTexSubImage2D(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glCopyTexSubImage2D((GLenum)ga(c, m, 0), (GLint)ga(c, m, 1), (GLint)ga(c, m, 2), (GLint)ga(c, m, 3), (GLint)ga(c, m, 4), (GLint)ga(c, m, 5), (GLsizei)ga(c, m, 6), (GLsizei)ga(c, m, 7));
}

static void t_glUniform2iv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniform2iv");
    c->r[0] = 0;
}

static void t_glGetAttribLocation(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glGetAttribLocation");
    c->r[0] = 0;
}

static void t_glIsQuery(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glIsQuery");
    c->r[0] = 0;
}

static void t_glMultMatrixx(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glMultMatrixx((const GLfixed *)gp(m, ga(c, m, 0)));
}

static void t_glTexEnvx(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glTexEnvx((GLenum)ga(c, m, 0), (GLenum)ga(c, m, 1), (GLfixed)ga(c, m, 2));
}

static void t_glPushMatrix(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glPushMatrix();
}

static void t_glVertexBindingDivisor(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glVertexBindingDivisor");
    c->r[0] = 0;
}

static void t_glTexParameteriv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glTexParameteriv((GLenum)ga(c, m, 0), (GLenum)ga(c, m, 1), (const GLint *)gp(m, ga(c, m, 2)));
}

static void t_glLogicOp(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glLogicOp((GLenum)ga(c, m, 0));
}

static void t_glBindSampler(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glBindSampler");
    c->r[0] = 0;
}

static void t_glClipPlanex(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glClipPlanex((GLenum)ga(c, m, 0), (const GLfixed *)gp(m, ga(c, m, 1)));
}

static void t_glFrustumf(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glFrustumf((GLfloat)gf(ga(c, m, 0)), (GLfloat)gf(ga(c, m, 1)), (GLfloat)gf(ga(c, m, 2)), (GLfloat)gf(ga(c, m, 3)), (GLfloat)gf(ga(c, m, 4)), (GLfloat)gf(ga(c, m, 5)));
}

static void t_glTranslatex(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glTranslatex((GLfixed)ga(c, m, 0), (GLfixed)ga(c, m, 1), (GLfixed)ga(c, m, 2));
}

static void t_glVertexPointer(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glVertexPointer((GLint)ga(c, m, 0), (GLenum)ga(c, m, 1), (GLsizei)ga(c, m, 2), (const void *)gp(m, ga(c, m, 3)));
}

static void t_glGenTextures(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glGenTextures((GLsizei)ga(c, m, 0), (GLuint *)gp(m, ga(c, m, 1)));
}

static void t_glBindProgramPipeline(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glBindProgramPipeline");
    c->r[0] = 0;
}

static void t_glVertexAttribPointer(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glVertexAttribPointer");
    c->r[0] = 0;
}

static void t_glScissor(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glScissor((GLint)ga(c, m, 0), (GLint)ga(c, m, 1), (GLsizei)ga(c, m, 2), (GLsizei)ga(c, m, 3));
}

static void t_glAttachShader(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glAttachShader");
    c->r[0] = 0;
}

static void t_glGetShaderiv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glGetShaderiv");
    c->r[0] = 0;
}

static void t_glBindBuffer(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glBindBuffer((GLenum)ga(c, m, 0), (GLuint)ga(c, m, 1));
}

static void t_glRotatex(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glRotatex((GLfixed)ga(c, m, 0), (GLfixed)ga(c, m, 1), (GLfixed)ga(c, m, 2), (GLfixed)ga(c, m, 3));
}

static void t_glLoadIdentity(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glLoadIdentity();
}

static void t_glGetProgramiv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glGetProgramiv");
    c->r[0] = 0;
}

static void t_glLinkProgram(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glLinkProgram");
    c->r[0] = 0;
}

static void t_glCompressedTexImage2D(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glCompressedTexImage2D((GLenum)ga(c, m, 0), (GLint)ga(c, m, 1), (GLenum)ga(c, m, 2), (GLsizei)ga(c, m, 3), (GLsizei)ga(c, m, 4), (GLint)ga(c, m, 5), (GLsizei)ga(c, m, 6), (const void *)gp(m, ga(c, m, 7)));
}

static void t_glDeleteQueries(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glDeleteQueries");
    c->r[0] = 0;
}

static void t_glTexEnvf(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glTexEnvf((GLenum)ga(c, m, 0), (GLenum)ga(c, m, 1), (GLfloat)gf(ga(c, m, 2)));
}

static void t_glGetString(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = gl_return_cstr(m, (const char *)glGetString((GLenum)ga(c, m, 0)));
}

static void t_eglSwapBuffers(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)eglSwapBuffers((EGLDisplay)ga(c, m, 0), (EGLSurface)ga(c, m, 1));
}

static void t_glStencilOp(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glStencilOp((GLenum)ga(c, m, 0), (GLenum)ga(c, m, 1), (GLenum)ga(c, m, 2));
}

static void t_glTexImage3D(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glTexImage3D");
    c->r[0] = 0;
}

static void t_eglGetProcAddress(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)eglGetProcAddress((const char *)gp(m, ga(c, m, 0)));
}

static void t_glClipPlanef(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glClipPlanef((GLenum)ga(c, m, 0), (const GLfloat *)gp(m, ga(c, m, 1)));
}

static void t_eglCreatePbufferSurface(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)eglCreatePbufferSurface((EGLDisplay)ga(c, m, 0), (EGLConfig)ga(c, m, 1), (const EGLint *)gp(m, ga(c, m, 2)));
}

static void t_glTexSubImage2D(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glTexSubImage2D((GLenum)ga(c, m, 0), (GLint)ga(c, m, 1), (GLint)ga(c, m, 2), (GLint)ga(c, m, 3), (GLsizei)ga(c, m, 4), (GLsizei)ga(c, m, 5), (GLenum)ga(c, m, 6), (GLenum)ga(c, m, 7), (const void *)gp(m, ga(c, m, 8)));
}

static void t_eglGetCurrentContext(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)eglGetCurrentContext();
}

static void t_eglGetConfigs(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)eglGetConfigs((EGLDisplay)ga(c, m, 0), (EGLConfig *)gp(m, ga(c, m, 1)), (EGLint)ga(c, m, 2), (EGLint *)gp(m, ga(c, m, 3)));
}

static void t_glSamplerParameteriv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glSamplerParameteriv");
    c->r[0] = 0;
}

static void t_glEnableVertexAttribArray(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glEnableVertexAttribArray");
    c->r[0] = 0;
}

static void t_glUniform1uiv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniform1uiv");
    c->r[0] = 0;
}

static void t_glDeleteSamplers(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glDeleteSamplers");
    c->r[0] = 0;
}

static void t_glVertexAttribFormat(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glVertexAttribFormat");
    c->r[0] = 0;
}

static void t_glNormal3f(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glNormal3f((GLfloat)gf(ga(c, m, 0)), (GLfloat)gf(ga(c, m, 1)), (GLfloat)gf(ga(c, m, 2)));
}

static void t_glLoadMatrixx(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glLoadMatrixx((const GLfixed *)gp(m, ga(c, m, 0)));
}

static void t_glCompressedTexImage3D(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glCompressedTexImage3D");
    c->r[0] = 0;
}

static void t_glLightModelfv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glLightModelfv((GLenum)ga(c, m, 0), (const GLfloat *)gp(m, ga(c, m, 1)));
}

static void t_glScalef(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glScalef((GLfloat)gf(ga(c, m, 0)), (GLfloat)gf(ga(c, m, 1)), (GLfloat)gf(ga(c, m, 2)));
}

static void t_glBindBufferBase(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glBindBufferBase");
    c->r[0] = 0;
}

static void t_glActiveTexture(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glActiveTexture((GLenum)ga(c, m, 0));
}

static void t_glBindImageTexture(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glBindImageTexture");
    c->r[0] = 0;
}

static void t_glTexEnvfv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glTexEnvfv((GLenum)ga(c, m, 0), (GLenum)ga(c, m, 1), (const GLfloat *)gp(m, ga(c, m, 2)));
}

static void t_glPolygonOffsetx(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glPolygonOffsetx((GLfixed)ga(c, m, 0), (GLfixed)ga(c, m, 1));
}

static void t_glLightx(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glLightx((GLenum)ga(c, m, 0), (GLenum)ga(c, m, 1), (GLfixed)ga(c, m, 2));
}

static void t_glTexParameterfv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glTexParameterfv((GLenum)ga(c, m, 0), (GLenum)ga(c, m, 1), (const GLfloat *)gp(m, ga(c, m, 2)));
}

static void t_eglTerminate(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)eglTerminate((EGLDisplay)ga(c, m, 0));
}

static void t_glGetQueryiv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glGetQueryiv");
    c->r[0] = 0;
}

static void t_glLightfv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glLightfv((GLenum)ga(c, m, 0), (GLenum)ga(c, m, 1), (const GLfloat *)gp(m, ga(c, m, 2)));
}

static void t_glGenQueries(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glGenQueries");
    c->r[0] = 0;
}

static void t_glShaderBinary(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glShaderBinary");
    c->r[0] = 0;
}

static void t_glUniform1iv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniform1iv");
    c->r[0] = 0;
}

static void t_eglDestroySurface(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)eglDestroySurface((EGLDisplay)ga(c, m, 0), (EGLSurface)ga(c, m, 1));
}

static void t_glDrawArrays(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glDrawArrays((GLenum)ga(c, m, 0), (GLint)ga(c, m, 1), (GLsizei)ga(c, m, 2));
}

static void t_glCopyTexImage2D(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glCopyTexImage2D((GLenum)ga(c, m, 0), (GLint)ga(c, m, 1), (GLenum)ga(c, m, 2), (GLint)ga(c, m, 3), (GLint)ga(c, m, 4), (GLsizei)ga(c, m, 5), (GLsizei)ga(c, m, 6), (GLint)ga(c, m, 7));
}

static void t_glCreateProgram(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glCreateProgram");
    c->r[0] = 0;
}

static void t_eglGetCurrentSurface(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)eglGetCurrentSurface((EGLint)ga(c, m, 0));
}

static void t_glAlphaFuncx(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glAlphaFuncx((GLenum)ga(c, m, 0), (GLfixed)ga(c, m, 1));
}

static void t_glCompileShader(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glCompileShader");
    c->r[0] = 0;
}

static void t_glStencilOpSeparate(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glStencilOpSeparate");
    c->r[0] = 0;
}

static void t_glPolygonOffset(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glPolygonOffset((GLfloat)gf(ga(c, m, 0)), (GLfloat)gf(ga(c, m, 1)));
}

static void t_glFramebufferParameteri(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glFramebufferParameteri");
    c->r[0] = 0;
}

static void t_glDeleteShader(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glDeleteShader");
    c->r[0] = 0;
}

static void t_glTexParameterx(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glTexParameterx((GLenum)ga(c, m, 0), (GLenum)ga(c, m, 1), (GLfixed)ga(c, m, 2));
}

static void t_eglQueryContext(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)eglQueryContext((EGLDisplay)ga(c, m, 0), (EGLContext)ga(c, m, 1), (EGLint)ga(c, m, 2), (EGLint *)gp(m, ga(c, m, 3)));
}

static void t_glFogfv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glFogfv((GLenum)ga(c, m, 0), (const GLfloat *)gp(m, ga(c, m, 1)));
}

static void t_glVertexAttribDivisor(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glVertexAttribDivisor");
    c->r[0] = 0;
}

static void t_glGetProgramInfoLog(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glGetProgramInfoLog");
    c->r[0] = 0;
}

static void t_glScalex(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glScalex((GLfixed)ga(c, m, 0), (GLfixed)ga(c, m, 1), (GLfixed)ga(c, m, 2));
}

static void t_glBindAttribLocation(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glBindAttribLocation");
    c->r[0] = 0;
}

static void t_glActiveShaderProgram(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glActiveShaderProgram");
    c->r[0] = 0;
}

static void t_glMaterialxv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glMaterialxv((GLenum)ga(c, m, 0), (GLenum)ga(c, m, 1), (const GLfixed *)gp(m, ga(c, m, 2)));
}

static void t_glUniform4uiv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniform4uiv");
    c->r[0] = 0;
}

static void t_glVertexAttribBinding(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glVertexAttribBinding");
    c->r[0] = 0;
}

static void t_glLightf(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glLightf((GLenum)ga(c, m, 0), (GLenum)ga(c, m, 1), (GLfloat)gf(ga(c, m, 2)));
}

static void t_glUniform3uiv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniform3uiv");
    c->r[0] = 0;
}

static void t_glTexStorage3D(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glTexStorage3D");
    c->r[0] = 0;
}

static void t_glReadPixels(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glReadPixels((GLint)ga(c, m, 0), (GLint)ga(c, m, 1), (GLsizei)ga(c, m, 2), (GLsizei)ga(c, m, 3), (GLenum)ga(c, m, 4), (GLenum)ga(c, m, 5), (void *)gp(m, ga(c, m, 6)));
}

static void t_glDeleteVertexArrays(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glDeleteVertexArrays");
    c->r[0] = 0;
}

static void t_glBindVertexArray(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glBindVertexArray");
    c->r[0] = 0;
}

static void t_glColorMask(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glColorMask((GLboolean)ga(c, m, 0), (GLboolean)ga(c, m, 1), (GLboolean)ga(c, m, 2), (GLboolean)ga(c, m, 3));
}

static void t_glTexEnvxv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glTexEnvxv((GLenum)ga(c, m, 0), (GLenum)ga(c, m, 1), (const GLfixed *)gp(m, ga(c, m, 2)));
}

static void t_glGetBooleanv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glGetBooleanv((GLenum)ga(c, m, 0), (GLboolean *)gp(m, ga(c, m, 1)));
}

static void t_glUniform4f(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniform4f");
    c->r[0] = 0;
}

static void t_glMatrixMode(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glMatrixMode((GLenum)ga(c, m, 0));
}

static void t_glTranslatef(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glTranslatef((GLfloat)gf(ga(c, m, 0)), (GLfloat)gf(ga(c, m, 1)), (GLfloat)gf(ga(c, m, 2)));
}

static void t_glUniform4fv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniform4fv");
    c->r[0] = 0;
}

static void t_glColorPointer(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glColorPointer((GLint)ga(c, m, 0), (GLenum)ga(c, m, 1), (GLsizei)ga(c, m, 2), (const void *)gp(m, ga(c, m, 3)));
}

static void t_glFinish(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glFinish();
}

static void t_glDepthFunc(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glDepthFunc((GLenum)ga(c, m, 0));
}

static void t_glUniformMatrix2x3fv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniformMatrix2x3fv");
    c->r[0] = 0;
}

static void t_glUniformMatrix2x4fv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniformMatrix2x4fv");
    c->r[0] = 0;
}

static void t_glDeleteTextures(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glDeleteTextures((GLsizei)ga(c, m, 0), (const GLuint *)gp(m, ga(c, m, 1)));
}

static void t_glClearColor(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glClearColor((GLfloat)gf(ga(c, m, 0)), (GLfloat)gf(ga(c, m, 1)), (GLfloat)gf(ga(c, m, 2)), (GLfloat)gf(ga(c, m, 3)));
}

static void t_glCompressedTexSubImage2D(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glCompressedTexSubImage2D((GLenum)ga(c, m, 0), (GLint)ga(c, m, 1), (GLint)ga(c, m, 2), (GLint)ga(c, m, 3), (GLsizei)ga(c, m, 4), (GLsizei)ga(c, m, 5), (GLenum)ga(c, m, 6), (GLsizei)ga(c, m, 7), (const void *)gp(m, ga(c, m, 8)));
}

static void t_glDrawElements(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glDrawElements((GLenum)ga(c, m, 0), (GLsizei)ga(c, m, 1), (GLenum)ga(c, m, 2), (const void *)gp(m, ga(c, m, 3)));
}

static void t_eglCreateWindowSurface(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)eglCreateWindowSurface((EGLDisplay)ga(c, m, 0), (EGLConfig)ga(c, m, 1), (EGLNativeWindowType)ga(c, m, 2), (const EGLint *)gp(m, ga(c, m, 3)));
}

static void t_eglBindAPI(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)eglBindAPI((EGLenum)ga(c, m, 0));
}

static void t_glUniform2uiv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniform2uiv");
    c->r[0] = 0;
}

static void t_glBindVertexBuffer(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glBindVertexBuffer");
    c->r[0] = 0;
}

static void t_glDetachShader(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glDetachShader");
    c->r[0] = 0;
}

static void t_glReadBuffer(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glReadBuffer");
    c->r[0] = 0;
}

static void t_glHint(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glHint((GLenum)ga(c, m, 0), (GLenum)ga(c, m, 1));
}

static void t_glCreateShader(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glCreateShader");
    c->r[0] = 0;
}

static void t_glUniformMatrix3x2fv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniformMatrix3x2fv");
    c->r[0] = 0;
}

static void t_glTexStorage2DMultisample(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glTexStorage2DMultisample");
    c->r[0] = 0;
}

static void t_glUniformMatrix4fv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniformMatrix4fv");
    c->r[0] = 0;
}

static void t_glUniformMatrix3x4fv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniformMatrix3x4fv");
    c->r[0] = 0;
}

static void t_glGetActiveUniform(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glGetActiveUniform");
    c->r[0] = 0;
}

static void t_glSamplerParameterfv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glSamplerParameterfv");
    c->r[0] = 0;
}

static void t_glStencilMask(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glStencilMask((GLuint)ga(c, m, 0));
}

static void t_glRenderbufferStorageMultisample(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glRenderbufferStorageMultisample");
    c->r[0] = 0;
}

static void t_glTexStorage2D(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glTexStorage2D");
    c->r[0] = 0;
}

static void t_glSampleMaski(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glSampleMaski");
    c->r[0] = 0;
}

static void t_glLineWidthx(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glLineWidthx((GLfixed)ga(c, m, 0));
}

static void t_glShadeModel(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glShadeModel((GLenum)ga(c, m, 0));
}

static void t_glGetError(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)glGetError();
}

static void t_glNormal3x(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glNormal3x((GLfixed)ga(c, m, 0), (GLfixed)ga(c, m, 1), (GLfixed)ga(c, m, 2));
}

static void t_glUniform1i(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniform1i");
    c->r[0] = 0;
}

static void t_glMultiTexCoord4x(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glMultiTexCoord4x((GLenum)ga(c, m, 0), (GLfixed)ga(c, m, 1), (GLfixed)ga(c, m, 2), (GLfixed)ga(c, m, 3), (GLfixed)ga(c, m, 4));
}

static void t_glFrontFace(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glFrontFace((GLenum)ga(c, m, 0));
}

static void t_eglBindTexImage(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)eglBindTexImage((EGLDisplay)ga(c, m, 0), (EGLSurface)ga(c, m, 1), (EGLint)ga(c, m, 2));
}

static void t_eglInitialize(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)eglInitialize((EGLDisplay)ga(c, m, 0), (EGLint *)gp(m, ga(c, m, 1)), (EGLint *)gp(m, ga(c, m, 2)));
}

static void t_glLoadMatrixf(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glLoadMatrixf((const GLfloat *)gp(m, ga(c, m, 0)));
}

static void t_glUniformMatrix4x2fv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniformMatrix4x2fv");
    c->r[0] = 0;
}

static void t_glUniformMatrix4x3fv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniformMatrix4x3fv");
    c->r[0] = 0;
}

static void t_glVertexAttribIFormat(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glVertexAttribIFormat");
    c->r[0] = 0;
}

static void t_glViewport(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glViewport((GLint)ga(c, m, 0), (GLint)ga(c, m, 1), (GLsizei)ga(c, m, 2), (GLsizei)ga(c, m, 3));
}

static void t_glTransformFeedbackVaryings(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glTransformFeedbackVaryings");
    c->r[0] = 0;
}

static void t_glTexCoordPointer(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glTexCoordPointer((GLint)ga(c, m, 0), (GLenum)ga(c, m, 1), (GLsizei)ga(c, m, 2), (const void *)gp(m, ga(c, m, 3)));
}

static void t_glUniform2fv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniform2fv");
    c->r[0] = 0;
}

static void t_glDepthRangef(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glDepthRangef((GLfloat)gf(ga(c, m, 0)), (GLfloat)gf(ga(c, m, 1)));
}

static void t_glEndQuery(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glEndQuery");
    c->r[0] = 0;
}

static void t_glEnable(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glEnable((GLenum)ga(c, m, 0));
}

static void t_glUniform3fv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glUniform3fv");
    c->r[0] = 0;
}

static void t_glGenBuffers(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glGenBuffers((GLsizei)ga(c, m, 0), (GLuint *)gp(m, ga(c, m, 1)));
}

static void t_glTexParameterxv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glTexParameterxv((GLenum)ga(c, m, 0), (GLenum)ga(c, m, 1), (const GLfixed *)gp(m, ga(c, m, 2)));
}

static void t_glDeleteProgram(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glDeleteProgram");
    c->r[0] = 0;
}

static void t_glBlendFunc(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glBlendFunc((GLenum)ga(c, m, 0), (GLenum)ga(c, m, 1));
}

static void t_glColor4x(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glColor4x((GLfixed)ga(c, m, 0), (GLfixed)ga(c, m, 1), (GLfixed)ga(c, m, 2), (GLfixed)ga(c, m, 3));
}

static void t_glGetFloatv(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    glGetFloatv((GLenum)ga(c, m, 0), (GLfloat *)gp(m, ga(c, m, 1)));
}

static void t_glShaderSource(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glShaderSource");
    c->r[0] = 0;
}

static void t_eglReleaseTexImage(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    c->r[0] = (uint32_t)eglReleaseTexImage((EGLDisplay)ga(c, m, 0), (EGLSurface)ga(c, m, 1), (EGLint)ga(c, m, 2));
}

static void t_glBindBufferRange(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glBindBufferRange");
    c->r[0] = 0;
}

static void t_glBeginQuery(GuestCpu *c, GuestMem *m, void *u) {
    (void)c; (void)m; (void)u;
    gl_unimplemented("glBeginQuery");
    c->r[0] = 0;
}

const GlThunk g_gl_thunks[] = {
    { "glRenderbufferStorage", t_glRenderbufferStorage },
    { "glGetRenderbufferParameteriv", t_glGetRenderbufferParameteriv },
    { "glGetFramebufferAttachmentParameteriv", t_glGetFramebufferAttachmentParameteriv },
    { "glBindRenderbuffer", t_glBindRenderbuffer },
    { "glGenerateMipmap", t_glGenerateMipmap },
    { "glBindFramebuffer", t_glBindFramebuffer },
    { "glFramebufferRenderbuffer", t_glFramebufferRenderbuffer },
    { "glDeleteRenderbuffers", t_glDeleteRenderbuffers },
    { "glFramebufferTexture2D", t_glFramebufferTexture2D },
    { "glGenRenderbuffers", t_glGenRenderbuffers },
    { "glCheckFramebufferStatus", t_glCheckFramebufferStatus },
    { "glIsRenderbuffer", t_glIsRenderbuffer },
    { "glIsFramebuffer", t_glIsFramebuffer },
    { "glDeleteFramebuffers", t_glDeleteFramebuffers },
    { "glGenFramebuffers", t_glGenFramebuffers },
    { "eglQueryString", t_eglQueryString },
    { "glStencilMaskSeparate", t_glStencilMaskSeparate },
    { "glUseProgramStages", t_glUseProgramStages },
    { "eglCreateContext", t_eglCreateContext },
    { "glFogxv", t_glFogxv },
    { "glFramebufferTextureLayer", t_glFramebufferTextureLayer },
    { "glClear", t_glClear },
    { "glClearColorx", t_glClearColorx },
    { "glNormalPointer", t_glNormalPointer },
    { "glMaterialfv", t_glMaterialfv },
    { "glStencilFunc", t_glStencilFunc },
    { "glFogf", t_glFogf },
    { "glMultiTexCoord4f", t_glMultiTexCoord4f },
    { "glUseProgram", t_glUseProgram },
    { "glRotatef", t_glRotatef },
    { "glDisable", t_glDisable },
    { "glCullFace", t_glCullFace },
    { "glClearStencil", t_glClearStencil },
    { "eglGetCurrentDisplay", t_eglGetCurrentDisplay },
    { "glDepthRangex", t_glDepthRangex },
    { "glDeleteBuffers", t_glDeleteBuffers },
    { "glLightModelxv", t_glLightModelxv },
    { "glOrthox", t_glOrthox },
    { "eglGetDisplay", t_eglGetDisplay },
    { "glEnableClientState", t_glEnableClientState },
    { "glColor4f", t_glColor4f },
    { "glPointSize", t_glPointSize },
    { "glGetUniformLocation", t_glGetUniformLocation },
    { "glDepthMask", t_glDepthMask },
    { "glDisableClientState", t_glDisableClientState },
    { "glVertexAttribIPointer", t_glVertexAttribIPointer },
    { "glBindTexture", t_glBindTexture },
    { "glLineWidth", t_glLineWidth },
    { "glPopMatrix", t_glPopMatrix },
    { "glMaterialx", t_glMaterialx },
    { "glCompressedTexSubImage3D", t_glCompressedTexSubImage3D },
    { "eglQuerySurface", t_eglQuerySurface },
    { "eglMakeCurrent", t_eglMakeCurrent },
    { "glBufferData", t_glBufferData },
    { "glClientActiveTexture", t_glClientActiveTexture },
    { "glBlendColor", t_glBlendColor },
    { "eglGetConfigAttrib", t_eglGetConfigAttrib },
    { "glFogx", t_glFogx },
    { "glTexEnvi", t_glTexEnvi },
    { "glGetShaderInfoLog", t_glGetShaderInfoLog },
    { "glLightModelx", t_glLightModelx },
    { "glGenVertexArrays", t_glGenVertexArrays },
    { "glTexSubImage3D", t_glTexSubImage3D },
    { "glTexImage2D", t_glTexImage2D },
    { "glClearDepthx", t_glClearDepthx },
    { "glLightxv", t_glLightxv },
    { "eglDestroyContext", t_eglDestroyContext },
    { "glDeleteProgramPipelines", t_glDeleteProgramPipelines },
    { "glGetQueryObjectuiv", t_glGetQueryObjectuiv },
    { "glOrthof", t_glOrthof },
    { "glGetIntegerv", t_glGetIntegerv },
    { "glMultMatrixf", t_glMultMatrixf },
    { "glBlendFuncSeparate", t_glBlendFuncSeparate },
    { "glUniform1f", t_glUniform1f },
    { "glTexParameteri", t_glTexParameteri },
    { "glMaterialf", t_glMaterialf },
    { "glUniform3iv", t_glUniform3iv },
    { "glStencilFuncSeparate", t_glStencilFuncSeparate },
    { "glGenProgramPipelines", t_glGenProgramPipelines },
    { "glPixelStorei", t_glPixelStorei },
    { "glDrawBuffers", t_glDrawBuffers },
    { "eglGetError", t_eglGetError },
    { "glUniform4iv", t_glUniform4iv },
    { "glUniform1fv", t_glUniform1fv },
    { "glBlendEquationSeparate", t_glBlendEquationSeparate },
    { "glAlphaFunc", t_glAlphaFunc },
    { "glBindTransformFeedback", t_glBindTransformFeedback },
    { "glUniformMatrix3fv", t_glUniformMatrix3fv },
    { "glUniformMatrix2fv", t_glUniformMatrix2fv },
    { "glLightModelf", t_glLightModelf },
    { "glClearDepthf", t_glClearDepthf },
    { "glDisableVertexAttribArray", t_glDisableVertexAttribArray },
    { "glCopyTexSubImage2D", t_glCopyTexSubImage2D },
    { "glUniform2iv", t_glUniform2iv },
    { "glGetAttribLocation", t_glGetAttribLocation },
    { "glIsQuery", t_glIsQuery },
    { "glMultMatrixx", t_glMultMatrixx },
    { "glTexEnvx", t_glTexEnvx },
    { "glPushMatrix", t_glPushMatrix },
    { "glVertexBindingDivisor", t_glVertexBindingDivisor },
    { "glTexParameteriv", t_glTexParameteriv },
    { "glLogicOp", t_glLogicOp },
    { "glBindSampler", t_glBindSampler },
    { "glClipPlanex", t_glClipPlanex },
    { "glFrustumf", t_glFrustumf },
    { "glTranslatex", t_glTranslatex },
    { "glVertexPointer", t_glVertexPointer },
    { "glGenTextures", t_glGenTextures },
    { "glBindProgramPipeline", t_glBindProgramPipeline },
    { "glVertexAttribPointer", t_glVertexAttribPointer },
    { "glScissor", t_glScissor },
    { "glAttachShader", t_glAttachShader },
    { "glGetShaderiv", t_glGetShaderiv },
    { "glBindBuffer", t_glBindBuffer },
    { "glRotatex", t_glRotatex },
    { "glLoadIdentity", t_glLoadIdentity },
    { "glGetProgramiv", t_glGetProgramiv },
    { "glLinkProgram", t_glLinkProgram },
    { "glCompressedTexImage2D", t_glCompressedTexImage2D },
    { "glDeleteQueries", t_glDeleteQueries },
    { "glTexEnvf", t_glTexEnvf },
    { "glGetString", t_glGetString },
    { "eglSwapBuffers", t_eglSwapBuffers },
    { "glStencilOp", t_glStencilOp },
    { "glTexImage3D", t_glTexImage3D },
    { "eglGetProcAddress", t_eglGetProcAddress },
    { "glClipPlanef", t_glClipPlanef },
    { "eglCreatePbufferSurface", t_eglCreatePbufferSurface },
    { "glTexSubImage2D", t_glTexSubImage2D },
    { "eglGetCurrentContext", t_eglGetCurrentContext },
    { "eglGetConfigs", t_eglGetConfigs },
    { "glSamplerParameteriv", t_glSamplerParameteriv },
    { "glEnableVertexAttribArray", t_glEnableVertexAttribArray },
    { "glUniform1uiv", t_glUniform1uiv },
    { "glDeleteSamplers", t_glDeleteSamplers },
    { "glVertexAttribFormat", t_glVertexAttribFormat },
    { "glNormal3f", t_glNormal3f },
    { "glLoadMatrixx", t_glLoadMatrixx },
    { "glCompressedTexImage3D", t_glCompressedTexImage3D },
    { "glLightModelfv", t_glLightModelfv },
    { "glScalef", t_glScalef },
    { "glBindBufferBase", t_glBindBufferBase },
    { "glActiveTexture", t_glActiveTexture },
    { "glBindImageTexture", t_glBindImageTexture },
    { "glTexEnvfv", t_glTexEnvfv },
    { "glPolygonOffsetx", t_glPolygonOffsetx },
    { "glLightx", t_glLightx },
    { "glTexParameterfv", t_glTexParameterfv },
    { "eglTerminate", t_eglTerminate },
    { "glGetQueryiv", t_glGetQueryiv },
    { "glLightfv", t_glLightfv },
    { "glGenQueries", t_glGenQueries },
    { "glShaderBinary", t_glShaderBinary },
    { "glUniform1iv", t_glUniform1iv },
    { "eglDestroySurface", t_eglDestroySurface },
    { "glDrawArrays", t_glDrawArrays },
    { "glCopyTexImage2D", t_glCopyTexImage2D },
    { "glCreateProgram", t_glCreateProgram },
    { "eglGetCurrentSurface", t_eglGetCurrentSurface },
    { "glAlphaFuncx", t_glAlphaFuncx },
    { "glCompileShader", t_glCompileShader },
    { "glStencilOpSeparate", t_glStencilOpSeparate },
    { "glPolygonOffset", t_glPolygonOffset },
    { "glFramebufferParameteri", t_glFramebufferParameteri },
    { "glDeleteShader", t_glDeleteShader },
    { "glTexParameterx", t_glTexParameterx },
    { "eglQueryContext", t_eglQueryContext },
    { "glFogfv", t_glFogfv },
    { "glVertexAttribDivisor", t_glVertexAttribDivisor },
    { "glGetProgramInfoLog", t_glGetProgramInfoLog },
    { "glScalex", t_glScalex },
    { "glBindAttribLocation", t_glBindAttribLocation },
    { "glActiveShaderProgram", t_glActiveShaderProgram },
    { "glMaterialxv", t_glMaterialxv },
    { "glUniform4uiv", t_glUniform4uiv },
    { "glVertexAttribBinding", t_glVertexAttribBinding },
    { "glLightf", t_glLightf },
    { "glUniform3uiv", t_glUniform3uiv },
    { "glTexStorage3D", t_glTexStorage3D },
    { "glReadPixels", t_glReadPixels },
    { "glDeleteVertexArrays", t_glDeleteVertexArrays },
    { "glBindVertexArray", t_glBindVertexArray },
    { "glColorMask", t_glColorMask },
    { "glTexEnvxv", t_glTexEnvxv },
    { "glGetBooleanv", t_glGetBooleanv },
    { "glUniform4f", t_glUniform4f },
    { "glMatrixMode", t_glMatrixMode },
    { "glTranslatef", t_glTranslatef },
    { "glUniform4fv", t_glUniform4fv },
    { "glColorPointer", t_glColorPointer },
    { "glFinish", t_glFinish },
    { "glDepthFunc", t_glDepthFunc },
    { "glUniformMatrix2x3fv", t_glUniformMatrix2x3fv },
    { "glUniformMatrix2x4fv", t_glUniformMatrix2x4fv },
    { "glDeleteTextures", t_glDeleteTextures },
    { "glClearColor", t_glClearColor },
    { "glCompressedTexSubImage2D", t_glCompressedTexSubImage2D },
    { "glDrawElements", t_glDrawElements },
    { "eglCreateWindowSurface", t_eglCreateWindowSurface },
    { "eglBindAPI", t_eglBindAPI },
    { "glUniform2uiv", t_glUniform2uiv },
    { "glBindVertexBuffer", t_glBindVertexBuffer },
    { "glDetachShader", t_glDetachShader },
    { "glReadBuffer", t_glReadBuffer },
    { "glHint", t_glHint },
    { "glCreateShader", t_glCreateShader },
    { "glUniformMatrix3x2fv", t_glUniformMatrix3x2fv },
    { "glTexStorage2DMultisample", t_glTexStorage2DMultisample },
    { "glUniformMatrix4fv", t_glUniformMatrix4fv },
    { "glUniformMatrix3x4fv", t_glUniformMatrix3x4fv },
    { "glGetActiveUniform", t_glGetActiveUniform },
    { "glSamplerParameterfv", t_glSamplerParameterfv },
    { "glStencilMask", t_glStencilMask },
    { "glRenderbufferStorageMultisample", t_glRenderbufferStorageMultisample },
    { "glTexStorage2D", t_glTexStorage2D },
    { "glSampleMaski", t_glSampleMaski },
    { "glLineWidthx", t_glLineWidthx },
    { "glShadeModel", t_glShadeModel },
    { "glGetError", t_glGetError },
    { "glNormal3x", t_glNormal3x },
    { "glUniform1i", t_glUniform1i },
    { "glMultiTexCoord4x", t_glMultiTexCoord4x },
    { "glFrontFace", t_glFrontFace },
    { "eglBindTexImage", t_eglBindTexImage },
    { "eglInitialize", t_eglInitialize },
    { "glLoadMatrixf", t_glLoadMatrixf },
    { "glUniformMatrix4x2fv", t_glUniformMatrix4x2fv },
    { "glUniformMatrix4x3fv", t_glUniformMatrix4x3fv },
    { "glVertexAttribIFormat", t_glVertexAttribIFormat },
    { "glViewport", t_glViewport },
    { "glTransformFeedbackVaryings", t_glTransformFeedbackVaryings },
    { "glTexCoordPointer", t_glTexCoordPointer },
    { "glUniform2fv", t_glUniform2fv },
    { "glDepthRangef", t_glDepthRangef },
    { "glEndQuery", t_glEndQuery },
    { "glEnable", t_glEnable },
    { "glUniform3fv", t_glUniform3fv },
    { "glGenBuffers", t_glGenBuffers },
    { "glTexParameterxv", t_glTexParameterxv },
    { "glDeleteProgram", t_glDeleteProgram },
    { "glBlendFunc", t_glBlendFunc },
    { "glColor4x", t_glColor4x },
    { "glGetFloatv", t_glGetFloatv },
    { "glShaderSource", t_glShaderSource },
    { "eglReleaseTexImage", t_eglReleaseTexImage },
    { "glBindBufferRange", t_glBindBufferRange },
    { "glBeginQuery", t_glBeginQuery },
    { 0, 0 }
};
const unsigned g_gl_thunk_count = 247;
