"""Generate the guest->host GL/EGL thunk layer.

The guest is 32-bit ARM softfp; the host is AArch64. Every GL import therefore
needs a shim that pulls arguments out of the guest's r0-r3 and stack, turns
guest pointers into host pointers, calls the real GLES entry point, and puts
the result back in r0. That is 247 functions of pure boilerplate, so it is
generated from devkitPro's own headers rather than written by hand -- which
also means the signatures cannot drift from the library we link against.

    .venv/Scripts/python.exe loader/mkglthunks.py [out.c]

AAPCS notes that matter here:
  * integers, pointers and (softfp) floats all travel in core registers
  * a 64-bit argument takes an even-aligned register pair, or 8-byte aligned
    stack -- so argument slots are not simply "one per parameter"
  * float returns come back in r0, doubles in r0:r1
"""
import os
import re
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
INC = "C:/devkitPro/portlibs/switch/include"

# The binary imports both the fixed-function and the shader entry points, so
# the GLES2/3 headers are needed too even though this is the gles1 build.
HEADERS = [
    INC + "/GLES/gl.h",
    INC + "/GLES/glext.h",
    INC + "/GLES2/gl2.h",
    INC + "/GLES2/gl2ext.h",
    INC + "/GLES3/gl3.h",
    INC + "/GLES3/gl31.h",
    INC + "/GLES3/gl32.h",
    INC + "/EGL/egl.h",
    INC + "/EGL/eglext.h",
]

# One capture per prototype: return type, name, argument list.
PROTO = re.compile(
    r"\b(?:GL_API|GL_APICALL|EGLAPI)\s+(.+?)\s*(?:GL_APIENTRY|EGLAPIENTRY)\s+"
    r"(\w+)\s*\(([^)]*)\)\s*;", re.S)


def imports_from_image():
    f = open(os.path.join(ROOT, "boz.s3e.unpacked"), "rb").read()
    h = struct.unpack_from("<19I", f, 0)
    p = h[3]
    _pad, _size, cnt = struct.unpack_from("<IIH", f, p)
    p += 10
    out = []
    for _ in range(cnt):
        e = f.index(b"\x00", p)
        out.append(f[p:e].decode("ascii", "replace"))
        p = e + 1
    return out


LINKABLE = ("GLES/gl.h", "GLES/glext.h", "EGL/egl.h", "EGL/eglext.h")


def parse_headers():
    protos = {}
    for path in HEADERS:
        try:
            src = open(path, encoding="utf-8", errors="replace").read()
        except OSError:
            continue
        linkable = any(path.endswith(x) for x in LINKABLE)
        for ret, name, args in PROTO.findall(src):
            if name in protos and protos[name][2]:
                continue          # a linkable declaration already won
            protos[name] = (ret.strip(), args.strip(), linkable)
    return protos


def classify(ctype):
    """-> 'v' void, 'p' pointer, 'd' 64-bit, 'f' float, 'i' 32-bit."""
    t = ctype.replace("const", "").strip()
    if "*" in t:
        return "p"
    t = t.split()[-1] if t.split() else t
    if t == "void":
        return "v"
    if t in ("GLfloat", "GLclampf", "float"):
        return "f"
    if t in ("GLdouble", "GLclampd", "double"):
        return "d"
    if t in ("GLint64", "GLuint64", "EGLTime", "GLsync"):
        return "d"
    return "i"


def arg_type(a):
    """Parameter declaration -> just its type, keeping pointer stars."""
    a = a.strip()
    if a in ("void", ""):
        return a
    m = re.match(r"^(.*?)(\w+)\s*(\[\s*\d*\s*\])?$", a, re.S)
    if not m:
        return a
    t = m.group(1).strip()
    return t if t else a


def split_args(args):
    if not args or args.strip() in ("void", ""):
        return []
    out, depth, cur = [], 0, ""
    for ch in args:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur)
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur)
    return [a.strip() for a in out]


def emit(names, protos, out_path):
    L = []
    A = L.append
    A('/* GENERATED by loader/mkglthunks.py -- do not edit by hand.')
    A(' *')
    A(' * Guest (ARM32 softfp) -> host (AArch64) shims for the GL/EGL imports.')
    A(' * Regenerate after changing the import set or the GLES headers. */')
    A('#include <stdint.h>')
    A('#include <string.h>')
    A('')
    A('#include <GLES/gl.h>')
    A('#include <GLES/glext.h>')
    A('#include <EGL/egl.h>')
    A('#include <EGL/eglext.h>')
    A('')
    A('#include "guest.h"')
    A('#include "gl_thunks.h"')
    A('')
    A('/* Argument fetch. Slots 0-3 are r0-r3, the rest come off the guest')
    A(' * stack. A 64-bit value needs an even-aligned pair. */')
    A('static uint32_t ga(GuestCpu *c, GuestMem *m, unsigned slot) {')
    A('    uint32_t v = 0;')
    A('    if (slot < 4)')
    A('        return c->r[slot];')
    A('    guest_ld32(m, c->r[GUEST_SP] + 4u * (slot - 4u), &v);')
    A('    return v;')
    A('}')
    A('')
    A('/* A guest pointer with no known extent: length 1 is enough to locate')
    A(' * the host mapping, and the region is contiguous from there. NULL')
    A(' * stays NULL so the driver sees the same thing the game passed. */')
    A('static void *gp(GuestMem *m, uint32_t addr) {')
    A('    return addr ? guest_ptr(m, addr, 1) : NULL;')
    A('}')
    A('')
    A('static float gf(uint32_t bits) {')
    A('    float f;')
    A('    memcpy(&f, &bits, 4);')
    A('    return f;')
    A('}')
    A('')

    made, skipped, stubs = [], [], []
    for nm in names:
        if nm not in protos:
            skipped.append(nm)
            continue
        ret, args, linkable = protos[nm]
        rk = classify(ret)
        # classify() wants a TYPE, and split_args yields whole parameter
        # declarations -- so `t.split()[-1]` was picking up the parameter NAME.
        # Every "GLfloat param" classified as 'i' and was passed as its raw bit
        # pattern reinterpreted as an integer: glTranslatef(1.0f) arrived as
        # 1065353216.0f. Pointers survived only because "*" is tested first.
        # The tell was gf(), the float reinterpreter, being emitted and never
        # called -- "warning: 'gf' defined but not used" at every build.
        ak = [classify(arg_type(a)) for a in split_args(args)]
        if "d" in ak or rk == "d":
            skipped.append(nm)          # 64-bit args: none in GLES1, punt
            continue

        A('static void t_%s(GuestCpu *c, GuestMem *m, void *u) {' % nm)
        A('    (void)c; (void)m; (void)u;')
        if not linkable:
            # Declared only by the GLES2/3 headers: not in libGLESv1_CM, and
            # this build should never reach it.
            A('    gl_unimplemented("%s");' % nm)
            A('    c->r[0] = 0;')
            A('}')
            A('')
            made.append(nm)
            stubs.append(nm)
            continue
        call, slot = [], 0
        for k in ak:
            if k == "p":
                call.append("gp(m, ga(c, m, %d))" % slot)
            elif k == "f":
                call.append("gf(ga(c, m, %d))" % slot)
            else:
                call.append("ga(c, m, %d)" % slot)
            slot += 1
        argstr = ", ".join(call)
        cast = [arg_type(a) for a in split_args(args)]
        # Cast each argument to its declared type so the compiler checks us.
        call2 = ", ".join("(%s)%s" % (t, v) for t, v in zip(cast, call)) \
            if cast and len(cast) == len(call) else argstr
        if rk == "v":
            A('    %s(%s);' % (nm, call2))
        elif rk == "f":
            A('    { float r = %s(%s); memcpy(&c->r[0], &r, 4); }' % (nm, call2))
        elif rk == "p":
            if "char" in ret or "GLubyte" in ret:
                A('    c->r[0] = gl_return_cstr(m, (const char *)%s(%s));'
                  % (nm, call2))
            else:
                # A host pointer cannot be represented to the guest; nothing in
                # the GLES1 path returns one, so make it loud rather than wrong.
                A('    gl_unsupported_ptr_return("%s");' % nm)
                A('    c->r[0] = 0;')
                A('    (void)0; /* %s */' % call2)
        else:
            A('    c->r[0] = (uint32_t)%s(%s);' % (nm, call2))
        A('}')
        A('')
        made.append(nm)

    A('const GlThunk g_gl_thunks[] = {')
    for nm in made:
        A('    { "%s", t_%s },' % (nm, nm))
    A('    { 0, 0 }')
    A('};')
    A('const unsigned g_gl_thunk_count = %d;' % len(made))
    A('')

    open(out_path, "w", newline="\n").write("\n".join(L))
    return made, skipped, stubs


def main(out_path):
    names = [n for n in imports_from_image()
             if n.startswith("gl") or n.startswith("egl")]
    protos = parse_headers()
    print("GL/EGL imports in image: %d" % len(names))
    print("prototypes parsed from headers: %d" % len(protos))
    made, skipped, stubs = emit(names, protos, out_path)
    print("thunks generated: %d (%d real, %d stubbed GLES2/3)"
          % (len(made), len(made) - len(stubs), len(stubs)))
    print("not generated:    %d" % len(skipped))
    if skipped:
        print("  " + " ".join(sorted(skipped)[:40]))
        if len(skipped) > 40:
            print("  ... and %d more" % (len(skipped) - 40))
    print("-> %s" % out_path)
    return 0


sys.exit(main(sys.argv[1] if len(sys.argv) > 1
              else os.path.join(ROOT, "jit", "gl_thunks.c")))
